// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuOkFWW-Lh4_baQwx9-bk4lJ1ube93ehc',
    appId: '1:874531864475:web:a3fb1ddbeeb628ba2f2b3e',
    messagingSenderId: '874531864475',
    projectId: 'flutterproject-9fa77',
    authDomain: 'flutterproject-9fa77.firebaseapp.com',
    storageBucket: 'flutterproject-9fa77.appspot.com',
    measurementId: 'G-7F5D4BJ93B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfNQEn2PTPUQfzEV-KrdEydAZfBQpnEw',
    appId: '1:874531864475:ios:1a2574c055894af92f2b3e',
    messagingSenderId: '874531864475',
    projectId: 'flutterproject-9fa77',
    storageBucket: 'flutterproject-9fa77.appspot.com',
    iosClientId: '874531864475-jk3s1vkrfe10nki2igfc9h4lha7du2ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfNQEn2PTPUQfzEV-KrdEydAZfBQpnEw',
    appId: '1:874531864475:ios:1a2574c055894af92f2b3e',
    messagingSenderId: '874531864475',
    projectId: 'flutterproject-9fa77',
    storageBucket: 'flutterproject-9fa77.appspot.com',
    iosClientId: '874531864475-jk3s1vkrfe10nki2igfc9h4lha7du2ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuOkFWW-Lh4_baQwx9-bk4lJ1ube93ehc',
    appId: '1:874531864475:web:a5dcd5c01ba8de0c2f2b3e',
    messagingSenderId: '874531864475',
    projectId: 'flutterproject-9fa77',
    authDomain: 'flutterproject-9fa77.firebaseapp.com',
    storageBucket: 'flutterproject-9fa77.appspot.com',
    measurementId: 'G-GDQLES3LH3',
  );

}